# settings for run.py
max_search: 20
input_file: input_2.csv
# settings for reviews
reviews:
  input_file: reviews_input.csv
  output_file: reviews_output.csv
  pages: 20
  dates_and_size: false
reviews_etsy:
  input_file: reviews_etsy_input.csv
  output_file: reviews_etsy_output.csv
  pages: 20
  split: "on"  # english: "on", polish: "w dniu"
  all_data: true
# settings for search.py
search:
  max_search: 5
  input: search_in.csv
  output: search_out.csv
# general settings
minimize: false
headless: false
browser: firefox